packages:
  - '.'
  - 'server'
  - 'server/adminUI'
  - 'website'
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - electron
  - electron-winstaller
  - esbuild
  - fibers
  - protobufjs
  - sharp
onlyBuiltDependencies:
  - ffmpeg-static
  - onnxruntime-node
